### ISSUE TITLE
Register AWS as a Relying Party Trust

### ISSUE THREAD

**Issue by eze1981** [samlidp/samlidp.io#10]
Hi guys,

I'm trying to register AWS as an SP but I'm getting the following error message:

 `The given metadata does not contain a public key for encrypting.`

This is the URL for AWS metadata file: 
https://signin.aws.amazon.com/static/saml-metadata.xml

And this is the URL for AWS documentation related to this: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_relying-party.html

Should AWS metadata file have an encryption key as the error message explains? I don't have control of the metadata file provided by AWS. Is there anything else that I can do to configure it as an SP?

Thank you,
Ezequiel

**Comment by eze1981** [comment]
This is why there is no encryption key in AWS metadata file: 

`The AWS implementation of SAML 2.0 federation does not support encrypted SAML assertions between the identity provider and AWS. However, the traffic between the customer's systems and AWS is transmitted over an encrypted (TLS) channel.`

Source: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html

**Comment by sitya** [comment]
Hi, we cannot, and do not want to disable encryption of assertions, so really sorry, but in this case it will not work.
