### ISSUE TITLE
Obtaining SamlIdP Private Key

### ISSUE THREAD

**Issue by gridworkz** [samlidp/samlidp.io#12]
How do I obtain the SamlIdP private key? I'm doing some testing at OneLogin. I also need to edit the IdP Metadata and change the nameid format to unspecified - it's currently transient.
Cheers,
Dave

**Comment by sitya** [comment]
> How do I obtain the SamlIdP private key? 

You cannot, but actually why do you think you would need the private key of the Identity Provider? You need the **public key** which can be found in the public metadata if the IdP. 

> I also need to edit the IdP Metadata and change the nameid format to unspecified - it's currently transient.

You cannot edit the metadata of the IdP, but if in the metadata of your SP you require `unspecified` the IdP should release in that format.

**Comment by gridworkz** [comment]
Hi Frank:

Cool, thanks a lot.

Cheers,Dave
