### ISSUE TITLE
Metadata not found

### ISSUE THREAD

**Issue by allanrevolorio** [samlidp/samlidp.io#13]
Hello

I am getting this error after making a SAML request:

> Unable to locate metadata for 'https://thm-dev.firelaycloud.com/o/catalyst-rest/saml/metadata'
> 
> If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator: 73c5494e8f

But the metadata is present in that URL

This is the SAML request message

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ONELOGIN_0aea6613-8566-4577-95de-63c31e562d9c"
                    Version="2.0"
                    IssueInstant="2018-05-28T21:40:19Z"
                    ProviderName="SP Java Example"
                    Destination="https://ltms.samlidp.io/saml2/idp/SSOService.php"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="https://thm-dev.firelaycloud.com/o/catalyst-rest/saml/acs">
  <saml:Issuer>https://thm-dev.firelaycloud.com/o/catalyst-rest/saml/metadata</saml:Issuer>
  <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
                      AllowCreate="true" />
  <samlp:RequestedAuthnContext Comparison="exact">
    <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

Please tell me what am I doing wrong

Thanks

**Comment by sitya** [comment]
Have you added the metadata of your SP to samlidp?

**Comment by allanrevolorio** [comment]
Is not possible to add the SP metadata in the IdP configuration page. See errors

![screenshot from 2018 05 29 14 42 53](https://user-images.githubusercontent.com/27861388/40659773-81879308-634f-11e8-857d-54a76821ec52.png)
![screenshot from 2018 05 29 14 44 05](https://user-images.githubusercontent.com/27861388/40659774-81a6550e-634f-11e8-915b-7114bf2bc9e6.png)

**Comment by sitya** [comment]
Hi, the messages are clear, please fix your XML metadata, then you will be able to add it.
