### ISSUE TITLE
Unhandled exception - Logout

### ISSUE THREAD

**Issue by admiralmaggie** [samlidp/samlidp.io#14]
I'm getting an Unhandled exception when posting to logout endpoint. Login works perfectly. Any ideas?

Tracking: 851004ef71

![image](https://user-images.githubusercontent.com/11258981/40663770-70dd6dde-6327-11e8-9aea-889d49e85577.png)

**Comment by sitya** [comment]
Did your SP sign the logoutrequest?

**Comment by admiralmaggie** [comment]
Thanks for getting back to me. No. Does it have to be signed?

**Comment by sitya** [comment]
> Thanks for getting back to me. No. Does it have to be signed?

Yes, but in your case the problem is that there is no SingleLogoutService endpoint in your SP's metadata. Logout request has been handled, the  user logged out, but the IdP cannot send back the LogoutResponse because it does not know where to send it.

**Comment by admiralmaggie** [comment]
Yup... That was it... Awesome! Thank you for your help!
