### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by ggrimbert** [samlidp/samlidp.io#15]
Hi,

I am trying to implement your service inside my app and I get the following page when I try to login : 
![image](https://user-images.githubusercontent.com/15869188/43200670-8873a3ca-9016-11e8-8f49-c114dea01471.png)

Also, it seems that logs are available, but where can I see them ?

**Comment by sitya** [comment]
You cannot load directly the endpoint URL like you did in the referenced
error, you have to come via your SP, AuthNRequest...etc.

**Comment by ggrimbert** [comment]
I'm using [passport-saml](https://github.com/bergie/passport-saml) ;I need an entryPoint, so what should it be ?
