### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by michaelstivala** [samlidp/samlidp.io#18]
Tracking Number: c79786ecd1

I am receiving an "Unhandled Exception" error message on the IdP (https://mindbeat.samlidp.io) after I try to login with a user.

It was working fine before I added some requestedAttributes:

```
<md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" FriendlyName="Email" isRequired="true"/>
<md:RequestedAttribute Name="urn:oid:2.5.4.42" FriendlyName="First Name" isRequired="true"/>
<md:RequestedAttribute Name="urn:oid:2.5.4.4" FriendlyName="Last Name" isRequired="true"/>
```

Though the login process completes, the payload doesn't contain the requestedAttributes.

Any help would be appreciated :)

**Comment by michaelstivala** [comment]
Actually, it seems like the following error is being returned by the IdP:

`SimpleSAML_Error_UnserializableException: Unable to extract public key`

**Comment by sitya** [comment]
Your metadata `http://5b81ec00.ngrok.io/saml/metadata` is invalid, there is `ds:X509Certificate` but it is empty.

**Comment by michaelstivala** [comment]
You're right... I broke that myself at some point! Thanks for pointing that out to me :) It's fixed my issue.

I've got a new issue now, but not sure if it's from the IdP, ngrok's tunnelling service or something in my app:

`The response was received at http://5b81ec00.ngrok.io:60/saml/acs instead of http://5b81ec00.ngrok.io/saml/acs`

Could you let me know if I should rule out the IdP?

**Comment by michaelstivala** [comment]
Actually, I'm pretty certain it's my own forwarding.

Thanks for your help!
