### ISSUE TITLE
Cannot add new custom service provider from https location.

### ISSUE THREAD

**Issue by LukaszSkwara** [samlidp/samlidp.io#2]
I cannot add new service provider from https location. For http it works fine.
Error message: The given URL is not reachable.
![image](https://cloud.githubusercontent.com/assets/17692845/26236045/0a84e512-3c77-11e7-9b28-03ba37148c28.png)
IdP: acaisoft.samlidp.io

**Comment by sitya** [comment]
What is the URL you would like to add SP from?

**Comment by LukaszSkwara** [comment]
https://attvr.acaisoft.net/api/saml/metadata

**Comment by sitya** [comment]
It seems form here, that there might be a misconfiguration. Is everything right with your SSL configuration at your webserver?

I have checked it with `curl` and `openssl s_client` from my computer and from samlidp.io server as well, and I got the same result (in addition my Firefox also has complained) : 

```
$ openssl s_client -connect attvr.acaisoft.net:443
CONNECTED(00000003)
depth=0 /C=PL/CN=*.acaisoft.net/emailAddress=kamil.litwiniuk@acaisoft.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /C=PL/CN=*.acaisoft.net/emailAddress=kamil.litwiniuk@acaisoft.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 /C=PL/CN=*.acaisoft.net/emailAddress=kamil.litwiniuk@acaisoft.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/C=PL/CN=*.acaisoft.net/emailAddress=kamil.litwiniuk@acaisoft.com
   i:/C=PL/O=Unizeto Technologies S.A./OU=Certum Certification Authority/CN=Certum Domain Validation CA SHA2
---
```

**Comment by LukaszSkwara** [comment]
The issue was with the certificate configuration. We needed to add 'Certum Domain Validation CA SHA2' into the signed server certificate.
Thank you for your help.
