### ISSUE TITLE
What is the correct metadata name?

### ISSUE THREAD

**Issue by mcnallys** [samlidp/samlidp.io#4]
https://patriotexcalibur.samlidp.io

I am trying to use the module SAML2 from https://github.com/i8beef/SAML2

but on redirect i always get a response of "unable to locate metadata"

What is the correct string I should be using to fetch the meta data? (service provider id element)

**Comment by sitya** [comment]
Hi, your IdP's metadata location, and entityID is the same: https://patriotexcalibur.samlidp.io/saml2/idp/metadata.php

**Comment by mcnallys** [comment]
I understand the issue now. Thanks for the quick response.
