### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by moraleslevi** [samlidp/samlidp.io#5]
I am trying to test against my IdP that I just created https://nogginlabs.samlidp.io but I am receiving an "Unhandled Exception" error message on the IdP-side.

Tracking number: 3eca0ea8ec

Any help as to what the issue is would be much appreciated!

**Comment by sitya** [comment]
In your SP's metadata there is `AuthnRequestsSigned="true"` but the AuthnRequest you sent to the IdP did not contain signature.

**Comment by moraleslevi** [comment]
Yes, thank you! Updated my SP metadata and it appears to be working. Thanks for the fast response!
